# Generated by Django 5.2.15 on 2026-06-17 10:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('maintenance', 'Maintenance'), ('strength', 'Strength'), ('muscle_gain', 'Muscle gain'), ('gradual_weight_loss', 'Gradual weight loss'), ('regularity', 'Regularity'), ('custom', 'Custom')], default='maintenance', max_length=32)),
                ('calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fat_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('carbs_target_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('workouts_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_weight_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_weight_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('active_from', models.DateField()),
                ('active_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_goal',
                'indexes': [models.Index(fields=['user', 'active_from'], name='profiles_us_user_id_3b4502_idx'), models.Index(fields=['user', 'active_to'], name='profiles_us_user_id_3c5c7f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('calorie_target__isnull', True), ('calorie_target__gte', 1), _connector='OR'), name='goal_calorie_target_positive_or_null'), models.CheckConstraint(condition=models.Q(('protein_target_g__isnull', True), ('protein_target_g__gte', 0), _connector='OR'), name='goal_protein_target_non_negative_or_null'), models.CheckConstraint(condition=models.Q(('fat_target_g__isnull', True), ('fat_target_g__gte', 0), _connector='OR'), name='goal_fat_target_non_negative_or_null'), models.CheckConstraint(condition=models.Q(('carbs_target_g__isnull', True), ('carbs_target_g__gte', 0), _connector='OR'), name='goal_carbs_target_non_negative_or_null'), models.CheckConstraint(condition=models.Q(('workouts_per_week__isnull', True), models.Q(('workouts_per_week__gte', 0), ('workouts_per_week__lte', 14)), _connector='OR'), name='goal_workouts_per_week_reasonable_or_null'), models.CheckConstraint(condition=models.Q(('target_weight_min__isnull', True), ('target_weight_min__gt', 0), _connector='OR'), name='goal_target_weight_min_positive_or_null'), models.CheckConstraint(condition=models.Q(('target_weight_max__isnull', True), ('target_weight_max__gt', 0), _connector='OR'), name='goal_target_weight_max_positive_or_null'), models.CheckConstraint(condition=models.Q(('target_weight_min__isnull', True), ('target_weight_max__isnull', True), ('target_weight_min__lte', models.F('target_weight_max')), _connector='OR'), name='goal_target_weight_range_valid'), models.CheckConstraint(condition=models.Q(('active_to__isnull', True), ('active_to__gte', models.F('active_from')), _connector='OR'), name='goal_active_period_valid')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar_key', models.CharField(blank=True, max_length=500)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=32)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='ru', max_length=16)),
                ('unit_system', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='metric', max_length=16)),
                ('week_starts_on', models.CharField(choices=[('monday', 'Monday'), ('sunday', 'Sunday')], default='monday', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_profile',
                'indexes': [models.Index(fields=['user'], name='profiles_us_user_id_04ef0b_idx'), models.Index(fields=['locale'], name='profiles_us_locale_f36273_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('height_cm__isnull', True), ('height_cm__gt', 0), _connector='OR'), name='profile_height_cm_positive_or_null')],
            },
        ),
    ]
