# Generated by Django 5.2.15 on 2026-06-18 06:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_exercise'),
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('local_device_id', models.UUIDField(blank=True, null=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('server_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_workouts', to='routines.routine')),
                ('source_routine_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_workouts', to='routines.routineday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workouts_workout',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('superset_group', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workout_exercises', to='exercises.exercise')),
                ('source_routine_exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_workout_exercises', to='routines.routineexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'db_table': 'workouts_workout_exercise',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('set_type', models.CharField(choices=[('warmup', 'Warmup'), ('working', 'Working'), ('failure', 'Failure'), ('drop_set', 'Drop set'), ('extra', 'Extra'), ('skipped', 'Skipped')], default='working', max_length=32)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rpe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rir', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.workoutexercise')),
            ],
            options={
                'db_table': 'workouts_workout_set',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'status'], name='workouts_wo_user_id_806cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'started_at'], name='workouts_wo_user_id_2a5c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'deleted_at'], name='workouts_wo_user_id_f94169_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['workout', 'position'], name='workouts_wo_workout_cb52aa_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutexercise',
            index=models.Index(fields=['exercise'], name='workouts_wo_exercis_cb66f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'position'), name='workout_exercise_position_unique_per_workout'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['workout_exercise', 'position'], name='workouts_wo_workout_e79cac_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['is_completed'], name='workouts_wo_is_comp_8caa43_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['deleted_at'], name='workouts_wo_deleted_b80a4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.UniqueConstraint(fields=('workout_exercise', 'position'), name='workout_set_position_unique_per_exercise'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gte', 0), _connector='OR'), name='workout_set_weight_non_negative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('distance_meters__isnull', True), ('distance_meters__gte', 0), _connector='OR'), name='workout_set_distance_non_negative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('rpe__isnull', True), models.Q(('rpe__gte', 1), ('rpe__lte', 10)), _connector='OR'), name='workout_set_rpe_between_1_and_10_or_null'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('rir__isnull', True), models.Q(('rir__gte', 0), ('rir__lte', 10)), _connector='OR'), name='workout_set_rir_between_0_and_10_or_null'),
        ),
    ]
