# Generated by Django 5.2.15 on 2026-06-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('max_weight', 'Max weight'), ('max_reps_with_weight', 'Max reps with weight'), ('best_set_volume', 'Best set volume'), ('estimated_one_rep_max', 'Estimated 1RM')], max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(max_length=32)),
                ('achieved_at', models.DateTimeField()),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
                ('workout_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='workouts.workoutset')),
            ],
            options={
                'db_table': 'workouts_personal_record',
                'ordering': ['exercise__name', 'record_type'],
                'indexes': [models.Index(fields=['user', 'is_current'], name='workouts_pe_user_id_7f806a_idx'), models.Index(fields=['user', 'exercise', 'record_type', 'is_current'], name='workouts_pe_user_id_f26587_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('user', 'exercise', 'record_type'), name='personal_record_one_current_per_type')],
            },
        ),
    ]
