# Generated by Django 5.2.15 on 2026-06-18 10:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('workouts', '0002_personalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('local_device_id__isnull', False)), fields=('user', 'local_device_id'), name='workout_local_device_id_unique_per_user'),
        ),
    ]
