# Generated by Django 5.2.15 on 2026-06-18 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('external', 'External'), ('ai', 'AI')], default='user', max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=160)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=160)),
                ('serving_size', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('serving_unit', models.CharField(blank=True, max_length=32)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_quality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=32)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_food',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('custom', 'Custom')], default='snack', max_length=32)),
                ('custom_name', models.CharField(blank=True, max_length=120)),
                ('eaten_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_meal',
                'ordering': ['meal_date', 'eaten_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name_snapshot', models.CharField(max_length=200)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('servings', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('serving_size_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calories_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbs_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai', 'AI'), ('copy', 'Copy')], default='manual', max_length=32)),
                ('ai_recognition_item_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_items', to='nutrition.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meal')),
            ],
            options={
                'db_table': 'nutrition_meal_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['owner', 'is_active'], name='nutrition_f_owner_i_23b031_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['source', 'is_active'], name='nutrition_f_source_92d9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='nutrition_f_name_caa2b0_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['barcode'], name='nutrition_f_barcode_395f4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('calories_per_100g__gte', 0)), name='food_calories_per_100g_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('protein_per_100g__gte', 0)), name='food_protein_per_100g_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('fat_per_100g__gte', 0)), name='food_fat_per_100g_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('carbs_per_100g__gte', 0)), name='food_carbs_per_100g_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('fiber_per_100g__isnull', True), ('fiber_per_100g__gte', 0), _connector='OR'), name='food_fiber_per_100g_non_negative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.CheckConstraint(condition=models.Q(('serving_size__isnull', True), ('serving_size__gt', 0), _connector='OR'), name='food_serving_size_positive_or_null'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'meal_date'], name='nutrition_m_user_id_91c3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='meal',
            index=models.Index(fields=['user', 'meal_type'], name='nutrition_m_user_id_7c2b15_idx'),
        ),
        migrations.AddIndex(
            model_name='mealitem',
            index=models.Index(fields=['meal', 'deleted_at'], name='nutrition_m_meal_id_f5b2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='mealitem',
            index=models.Index(fields=['food'], name='nutrition_m_food_id_737345_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('weight_g__isnull', True), ('weight_g__gt', 0), _connector='OR'), name='meal_item_weight_g_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.CheckConstraint(condition=models.Q(('servings__isnull', True), ('servings__gt', 0), _connector='OR'), name='meal_item_servings_positive_or_null'),
        ),
    ]
