# Generated by Django 5.2.15 on 2026-06-18 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecognition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_key', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, choices=[('no_response', 'No response'), ('timeout', 'Timeout'), ('invalid_format', 'Invalid format')], max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_recognitions', to='nutrition.meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_recognitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nutrition_food_recognition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodRecognitionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('ai_name', models.CharField(max_length=200)),
                ('ai_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('ai_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ai_calories_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ai_protein_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ai_fat_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ai_carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_name', models.CharField(max_length=200)),
                ('corrected_weight_g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_calories_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_protein_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_fat_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('corrected_carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user_corrected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.foodrecognition')),
            ],
            options={
                'db_table': 'nutrition_food_recognition_item',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='foodrecognition',
            index=models.Index(fields=['user', 'status'], name='nutrition_f_user_id_a78c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrecognition',
            index=models.Index(fields=['user', 'created_at'], name='nutrition_f_user_id_64b200_idx'),
        ),
        migrations.AddIndex(
            model_name='foodrecognitionitem',
            index=models.Index(fields=['recognition', 'position'], name='nutrition_f_recogni_7873e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='foodrecognitionitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_confidence__gte', 0), ('ai_confidence__lte', 1)), name='food_recognition_item_ai_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='foodrecognitionitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_weight_g__gt', 0)), name='food_recognition_item_ai_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='foodrecognitionitem',
            constraint=models.CheckConstraint(condition=models.Q(('corrected_weight_g__gt', 0)), name='food_recognition_item_corrected_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='foodrecognitionitem',
            constraint=models.CheckConstraint(condition=models.Q(('ai_calories_per_100g__gte', 0), ('ai_protein_per_100g__gte', 0), ('ai_fat_per_100g__gte', 0), ('ai_carbs_per_100g__gte', 0), ('corrected_calories_per_100g__gte', 0), ('corrected_protein_per_100g__gte', 0), ('corrected_fat_per_100g__gte', 0), ('corrected_carbs_per_100g__gte', 0)), name='food_recognition_item_nutrients_non_negative'),
        ),
    ]
