# Generated by Django 5.2.15 on 2026-06-18 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_foodrecognition_foodrecognitionitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='local_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='client_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='local_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='server_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(condition=models.Q(('local_device_id__isnull', False)), fields=('user', 'local_device_id'), name='meal_local_device_id_unique_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mealitem',
            constraint=models.UniqueConstraint(condition=models.Q(('local_device_id__isnull', False)), fields=('meal', 'local_device_id'), name='meal_item_local_device_id_unique_per_meal'),
        ),
    ]
