# Generated by Django 5.2.15 on 2026-06-18 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0002_exercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routines_routine',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('position', models.PositiveIntegerField()),
                ('planned_weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='routines.routine')),
            ],
            options={
                'db_table': 'routines_routine_day',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('planned_sets', models.PositiveSmallIntegerField(default=3)),
                ('rep_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rep_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('target_rir', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('superset_group', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routine_exercises', to='exercises.exercise')),
                ('routine_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='routines.routineday')),
            ],
            options={
                'db_table': 'routines_routine_exercise',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'is_active'], name='routines_ro_user_id_4eb614_idx'),
        ),
        migrations.AddIndex(
            model_name='routine',
            index=models.Index(fields=['user', 'deleted_at'], name='routines_ro_user_id_d7f7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='routineday',
            index=models.Index(fields=['routine', 'position'], name='routines_ro_routine_a2383c_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineday',
            constraint=models.UniqueConstraint(fields=('routine', 'position'), name='routine_day_position_unique_per_routine'),
        ),
        migrations.AddConstraint(
            model_name='routineday',
            constraint=models.CheckConstraint(condition=models.Q(('planned_weekday__isnull', True), models.Q(('planned_weekday__gte', 1), ('planned_weekday__lte', 7)), _connector='OR'), name='routine_day_planned_weekday_between_1_and_7_or_null'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['routine_day', 'position'], name='routines_ro_routine_825d27_idx'),
        ),
        migrations.AddIndex(
            model_name='routineexercise',
            index=models.Index(fields=['exercise'], name='routines_ro_exercis_798d81_idx'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.UniqueConstraint(fields=('routine_day', 'position'), name='routine_exercise_position_unique_per_day'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.CheckConstraint(condition=models.Q(('planned_sets__gte', 1)), name='routine_exercise_planned_sets_positive'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.CheckConstraint(condition=models.Q(('rep_min__isnull', True), ('rep_max__isnull', True), ('rep_min__lte', models.F('rep_max')), _connector='OR'), name='routine_exercise_rep_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_weight__isnull', True), ('target_weight__gte', 0), _connector='OR'), name='routine_exercise_target_weight_non_negative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_rpe__isnull', True), models.Q(('target_rpe__gte', 1), ('target_rpe__lte', 10)), _connector='OR'), name='routine_exercise_target_rpe_between_1_and_10_or_null'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.CheckConstraint(condition=models.Q(('target_rir__isnull', True), models.Q(('target_rir__gte', 0), ('target_rir__lte', 10)), _connector='OR'), name='routine_exercise_target_rir_between_0_and_10_or_null'),
        ),
    ]
