# Generated by Django 5.2.15 on 2026-06-18 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises_equipment',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='exercises_e_code_61d81d_idx'), models.Index(fields=['is_active'], name='exercises_e_is_acti_922a31_idx')],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='exercises.musclegroup')),
            ],
            options={
                'db_table': 'exercises_muscle_group',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='exercises_m_code_15ba77_idx'), models.Index(fields=['is_active'], name='exercises_m_is_acti_908894_idx')],
            },
        ),
    ]
