# Generated by Django 5.2.15 on 2026-06-18 06:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('tracking_type', models.CharField(choices=[('weight_reps', 'Weight + repetitions'), ('reps_only', 'Repetitions only'), ('time', 'Time'), ('distance_time', 'Distance + time'), ('bodyweight_added', 'Bodyweight + added weight'), ('bodyweight_assisted', 'Bodyweight + assistance'), ('calories', 'Calories'), ('custom', 'Custom')], default='weight_reps', max_length=32)),
                ('instructions', models.TextField(blank=True)),
                ('media_key', models.CharField(blank=True, max_length=500)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.equipment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
                ('primary_muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='exercises.musclegroup')),
            ],
            options={
                'db_table': 'exercises_exercise',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['owner', 'is_active'], name='exercises_e_owner_i_602e4b_idx'), models.Index(fields=['is_system', 'is_active'], name='exercises_e_is_syst_a67989_idx'), models.Index(fields=['name'], name='exercises_e_name_9bce89_idx'), models.Index(fields=['tracking_type'], name='exercises_e_trackin_0e605d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), ('is_system', False), _connector='OR'), name='system_exercise_has_no_owner'), models.CheckConstraint(condition=models.Q(('is_system', True), models.Q(('is_system', False), ('owner__isnull', False)), _connector='OR'), name='custom_exercise_has_owner')],
            },
        ),
    ]
